// ECFresh Mock Data - Ready-to-cook vegetables
import { Product, Category, Banner, ProductVariant } from "./types";

export const CATEGORIES: Category[] = [
  {
    id: "1",
    name: "Fresh Vegetables",
    slug: "fresh-vegetables", 
    image: "/api/placeholder/300/200",
    isActive: true,
  },
  {
    id: "2", 
    name: "Ready-to-Cook",
    slug: "ready-to-cook",
    image: "/api/placeholder/300/200", 
    isActive: true,
  },
  {
    id: "3",
    name: "Leafy Greens",
    slug: "leafy-greens",
    image: "/api/placeholder/300/200",
    isActive: true, 
  },
  {
    id: "4",
    name: "Exotic Vegetables", 
    slug: "exotic-vegetables",
    image: "/api/placeholder/300/200",
    isActive: true,
  },
];

export const BANNERS: Banner[] = [
  {
    id: "1",
    title: "Fresh Vegetables Delivered Daily",
    subtitle: "Ready-to-cook vegetables at your doorstep in Kochi",
    image: "/api/placeholder/800/200",
    ctaText: "Shop Now",
    ctaLink: "/products",
    isActive: true,
    order: 1,
  },
  {
    id: "2", 
    title: "Free Delivery Above ₹300",
    subtitle: "Get fresh vegetables with zero delivery charges",
    image: "/api/placeholder/800/200",
    ctaText: "Order Now", 
    ctaLink: "/products",
    isActive: true,
    order: 2,
  },
  {
    id: "3",
    title: "First Order Cashback ₹100",
    subtitle: "Earn instant cashback on your first purchase",
    image: "/api/placeholder/800/200",
    ctaText: "Claim Now",
    ctaLink: "/products",
    isActive: true,
    order: 3,
  },
];

const createVariants = (basePrice: number): ProductVariant[] => [
  {
    id: `var-${Math.random().toString(36).substr(2, 9)}`,
    weight: "300g",
    price: Math.round(basePrice * 0.6),
    originalPrice: Math.round(basePrice * 0.7),
    isInStock: true,
    isDefault: false,
  },
  {
    id: `var-${Math.random().toString(36).substr(2, 9)}`, 
    weight: "500g",
    price: basePrice,
    originalPrice: Math.round(basePrice * 1.1),
    isInStock: true,
    isDefault: true,
  },
  {
    id: `var-${Math.random().toString(36).substr(2, 9)}`,
    weight: "1kg", 
    price: Math.round(basePrice * 1.8),
    originalPrice: Math.round(basePrice * 2.0),
    isInStock: true,
    isDefault: false,
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Fresh Tomatoes",
    slug: "fresh-tomatoes",
    description: "Premium quality fresh tomatoes, perfect for cooking and salads. Sourced directly from local farms in Kerala. Rich in vitamins and antioxidants.",
    shortDescription: "Fresh, juicy tomatoes perfect for all your cooking needs",
    image: "/api/placeholder/400/400",
    images: ["/api/placeholder/400/400", "/api/placeholder/400/400", "/api/placeholder/400/400"],
    categoryId: "1", 
    category: CATEGORIES[0],
    variants: createVariants(80),
    tags: ["fresh", "organic", "local"],
    nutritionInfo: {
      calories: 18,
      protein: 0.9,
      carbs: 3.9,
      fat: 0.2,
    },
    preparationTime: "Ready to use",
    isActive: true,
    isFeatured: true,
    rating: 4.5,
    reviewCount: 128,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2", 
    name: "Cut & Cleaned Carrots",
    slug: "cut-cleaned-carrots",
    description: "Pre-washed and cut carrots ready for cooking. Save time with our ready-to-cook vegetables. Perfect for stir-fries, curries, and salads.",
    shortDescription: "Ready-to-cook carrots, washed and cut for convenience", 
    image: "/api/placeholder/400/400",
    images: ["/api/placeholder/400/400", "/api/placeholder/400/400"],
    categoryId: "2",
    category: CATEGORIES[1], 
    variants: createVariants(120),
    tags: ["ready-to-cook", "convenient", "fresh"],
    nutritionInfo: {
      calories: 41,
      protein: 0.9,
      carbs: 10,
      fat: 0.2,
    },
    preparationTime: "Ready to cook",
    isActive: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 89,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z", 
  },
  {
    id: "3",
    name: "Fresh Spinach Leaves",
    slug: "fresh-spinach-leaves",
    description: "Tender, fresh spinach leaves rich in iron and vitamins. Perfect for saag, salads, and healthy smoothies. Locally sourced and pesticide-free.",
    shortDescription: "Nutritious fresh spinach leaves, rich in iron",
    image: "/api/placeholder/400/400",
    images: ["/api/placeholder/400/400", "/api/placeholder/400/400"],
    categoryId: "3",
    category: CATEGORIES[2],
    variants: createVariants(60),
    tags: ["leafy", "nutritious", "iron-rich"],
    nutritionInfo: {
      calories: 23,
      protein: 2.9,
      carbs: 3.6,
      fat: 0.4,
    },
    preparationTime: "5 mins prep",
    isActive: true,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 67,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "4",
    name: "Baby Corn",
    slug: "baby-corn", 
    description: "Tender baby corn, perfect for Chinese dishes and stir-fries. Sweet and crunchy texture. Imported quality vegetables for your exotic cooking needs.",
    shortDescription: "Sweet and tender baby corn for exotic dishes",
    image: "/api/placeholder/400/400",
    images: ["/api/placeholder/400/400"],
    categoryId: "4",
    category: CATEGORIES[3],
    variants: createVariants(150),
    tags: ["exotic", "tender", "sweet"],
    nutritionInfo: {
      calories: 26,
      protein: 1.0,
      carbs: 6.0,
      fat: 0.1,
    },
    preparationTime: "Ready to cook",
    isActive: true,
    isFeatured: true,
    rating: 4.6,
    reviewCount: 45,
    createdAt: "2024-01-01T00:00:00Z", 
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "5",
    name: "Mixed Cut Vegetables",
    slug: "mixed-cut-vegetables",
    description: "A perfect mix of cut vegetables including carrots, beans, bell peppers, and cauliflower. Ready-to-cook convenience for busy households. Perfect for pulao, fried rice, and mixed vegetable curry.",
    shortDescription: "Ready-to-cook mixed vegetables for convenience",
    image: "/api/placeholder/400/400",
    images: ["/api/placeholder/400/400", "/api/placeholder/400/400"],
    categoryId: "2",
    category: CATEGORIES[1],
    variants: createVariants(180),
    tags: ["mixed", "convenient", "ready-to-cook"],
    nutritionInfo: {
      calories: 35,
      protein: 1.5,
      carbs: 7.0,
      fat: 0.3,
    },
    preparationTime: "Ready to cook",
    isActive: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 203,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "6",
    name: "Fresh Bell Peppers",
    slug: "fresh-bell-peppers",
    description: "Colorful mix of fresh bell peppers - red, yellow, and green. Perfect for adding color and crunch to your dishes. Rich in Vitamin C and antioxidants.",
    shortDescription: "Colorful mix of fresh bell peppers",
    image: "/api/placeholder/400/400", 
    images: ["/api/placeholder/400/400"],
    categoryId: "1",
    category: CATEGORIES[0],
    variants: createVariants(200),
    tags: ["colorful", "vitamin-c", "crunchy"],
    nutritionInfo: {
      calories: 31,
      protein: 1.0,
      carbs: 7.0,
      fat: 0.3,
    },
    preparationTime: "5 mins prep",
    isActive: true,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 72,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];

// Business Logic Constants
export const DELIVERY_FEE = 50;
export const FREE_DELIVERY_THRESHOLD = 300;
export const FIRST_ORDER_CASHBACK = 100;
export const REGULAR_CASHBACK_PERCENT = 10;
export const MIN_WALLET_USAGE = 300;
export const DELIVERY_SLOT_HOURS_AHEAD = 20;

// Mock user for development
export const MOCK_USER = {
  id: "user-1",
  phone: "+919876543210", 
  name: "Rahul Kumar",
  email: "rahul@example.com",
  addresses: [],
  walletBalance: 450,
  totalOrders: 3,
  isFirstOrder: false,
  loyaltyPoints: 250,
  createdAt: "2024-01-01T00:00:00Z",
};