// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gspfprcenxplonennlji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzcGZwcmNlbnhwbG9uZW5ubGppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTY1NDMsImV4cCI6MjA3MzkzMjU0M30.OP4vcxBvbtCRK23ilUUFaiyXhnl2sTGVzF0s3XwVSuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});